services:
  mongo:
    image: mongo:7.0
    container_name: practice20_db
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=YourMongoAdmin
      - MONGO_INITDB_ROOT_PASSWORD=1234
      - MONGO_INITDB_DATABASE=admin
    volumes:
      - mongodata:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 10s
  server:
    container_name: practice20_server
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3089:3089"
    environment:
      - NODE_ENV=production
      - PORT=3089
    depends_on:
      mongo:
        condition: service_healthy
    restart: on-failure
volumes:
  mongodata:
