events {
    worker_connections 1024;
}

http {
    upstream backend_servers {
        # Используем round-robin по умолчанию
        # Указываем имена сервисов из docker-compose
        server backend1:3095 max_fails=2 fail_timeout=10s;
        server backend2:3096 max_fails=2 fail_timeout=10s;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://backend_servers;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
